import { createServer } from "miragejs";

createServer({
  routes() {
    this.namespace = "api";

    this.get("/players", () => {
      return {
        players: [
          {
            playerName: "Cristiano Ronaldo",
            playerFirstName: "Cristiano",
            playerDate: "February 5, 1985",
            palayerAge: "(age 34)",
            playerHeight: "1.87 m",
            playerPosition: "Forward",
            playerNumber: "7",
            playerJoined: "2018",
            playerGoals: "56",
            playerImage: "img/players-position-1/forwardes/RONALDO_501x752.png",
            playerId: "#cristiano",
            isChecked: false,
            playerIdNo: 0,
            playerKeywords: ["cristiano", "ronaldo", "cristiano ronaldo"],
          },
          {
            playerName: "Paulo Dybala",
            playerFirstName: "Dybala",
            playerDate: "November 15, 1993",
            palayerAge: "(age 25)",
            playerHeight: "1.77 m",
            playerPosition: "Forward",
            playerNumber: "10",
            playerJoined: "2015",
            playerGoals: "16",
            playerImage: "img/players-position-1/forwardes/Dybala_501x752.png",
            playerId: "#dybala",
            isChecked: false,
            playerIdNo: 1,
            playerKeywords: ["dybala", "paulo", "paulo dybala"],
          },
          {
            playerName: "Douglas Costa",
            playerFirstName: "Costa",
            playerDate: "September 14, 1990",
            palayerAge: "(age 28)",
            playerHeight: "1.72 m",
            playerPosition: "Forward",
            playerNumber: "11",
            playerJoined: "2017",
            playerGoals: "1",
            playerImage: "img/players-position-1/forwardes/Costa_501x752.png",
            playerId: "#costa",
            isChecked: false,
            playerIdNo: 2,
            playerKeywords: ["costa", "douglas", "douglas costa"],
          },
          {
            playerName: "Federico Bernardeschi",
            playerFirstName: "Bernardeschi",
            playerDate: "February 16, 1994",
            palayerAge: "(age 25)",
            playerHeight: "1.85 m",
            playerPosition: "Forward",
            playerNumber: "33",
            playerJoined: "2017",
            playerGoals: "6",
            playerImage:
              "img/players-position-1/forwardes/Bernardeschi_501x752.png",
            playerId: "#bernardeschi",
            isChecked: false,
            playerIdNo: 3,
            playerKeywords: [
              "federico",
              "bernardeschi",
              "federico bernardeschi",
            ],
          },
          {
            playerName: "Mario Mandžukić",
            playerFirstName: "Mandzukic",
            playerDate: "May 26, 1988",
            palayerAge: "(age 32)",
            playerHeight: "1.90 m",
            playerPosition: "Forward",
            playerNumber: "17",
            playerJoined: "2015",
            playerGoals: "30",
            playerImage:
              "img/players-position-1/forwardes/MANDZUKIC_501x752.png",
            playerId: "#mandzukic",
            isChecked: false,
            playerIdNo: 4,
            playerKeywords: ["mario", "mandzukic", "mario mandzukic"],
          },
          {
            playerName: "Juan Cuadrado",
            playerFirstName: "Cuadrado",
            playerDate: "May 21, 1986",
            palayerAge: "(age 30)",
            playerHeight: "1.76 m",
            playerPosition: "Forward",
            playerNumber: "17",
            playerJoined: "2015",
            playerGoals: "5",
            playerImage:
              "img/players-position-1/forwardes/Cuadrado_501x752.png",
            playerId: "#cuadrado",
            isChecked: false,
            playerIdNo: 5,
            playerKeywords: ["juan", "cuadrado", "juan cuadrado"],
          },
          {
            playerName: "Moise Kean",
            playerFirstName: "Kean",
            playerDate: "June 25, 1997",
            palayerAge: "(age 18)",
            playerHeight: "1.82 m",
            playerPosition: "Forward",
            playerNumber: "18",
            playerJoined: "2016",
            playerGoals: "4",
            playerImage: "img/players-position-1/forwardes/KEAN_501x752.png",
            playerId: "#kean",
            isChecked: false,
            playerIdNo: 6,
            playerKeywords: ["moise", "kean", "moise kean"],
          },
          {
            playerName: "Rodrigo Bentancur",
            playerFirstName: "Bentancur",
            playerDate: "June 25, 1997",
            palayerAge: "(age 21)",
            playerHeight: "1.82 m",
            playerPosition: "Midfielder",
            playerNumber: "30",
            playerJoined: "2017",
            playerGoals: "2",
            playerImage:
              "img/players-position-1/midfielders/BENTANCUR_501x752.png",
            playerId: "#bentancur",
            isChecked: false,
            playerIdNo: 7,
            playerKeywords: ["rodrigo", "bentancur", "rodrigo bentancur"],
          },
          {
            playerName: "Sami Khedira",
            playerFirstName: "Khedira",
            playerDate: "April 4, 1987",
            palayerAge: "(age 31)",
            playerHeight: "1.89 m",
            playerPosition: "Midfielder",
            playerNumber: "6",
            playerJoined: "2015",
            playerGoals: "21",
            playerImage:
              "img/players-position-1/midfielders/KHEDIRA_501x752.png",
            playerId: "#khedira",
            isChecked: false,
            playerIdNo: 8,
            playerKeywords: ["sami", "khedira", "sami khedira"],
          },
          {
            playerName: "Emre Can",
            playerFirstName: "Can",
            playerDate: "April 4, 1987",
            palayerAge: "(age 25)",
            playerHeight: "1.84 m",
            playerPosition: "Midfielder",
            playerNumber: "23",
            playerJoined: "2018",
            playerGoals: "4",
            playerImage:
              "img/players-position-1/midfielders/EmreCan_501x752.png",
            playerId: "#can",
            isChecked: false,
            playerIdNo: 9,
            playerKeywords: ["emere", "can", "emere can"],
          },
          {
            playerName: "Blaise Matuidi",
            playerFirstName: "Matuidi",
            playerDate: "April 4, 1987",
            palayerAge: "(age 31)",
            playerHeight: "1.8 m",
            playerPosition: "Midfielder",
            playerNumber: "14",
            playerJoined: "2017",
            playerGoals: "6",
            playerImage:
              "img/players-position-1/midfielders/Matuidi_501x752.png",
            playerId: "#matuidi",
            isChecked: false,
            playerIdNo: 10,
            playerKeywords: ["blaise", "matuidi", "blaise matuidi"],
          },
          {
            playerName: "Miralem Pjanic",
            playerFirstName: "Pjanic",
            playerDate: "April 2, 1990",
            palayerAge: "(age 28)",
            playerHeight: "1.8 m",
            playerPosition: "Midfielder",
            playerNumber: "5",
            playerJoined: "2016",
            playerGoals: "18",
            playerImage:
              "img/players-position-1/midfielders/PJANIC_501x752.png",
            playerId: "#pjanic",
            isChecked: false,
            playerIdNo: 11,
            playerKeywords: ["miralem", "pjanic", "miralem pjanic"],
          },
          {
            playerName: "Giorgio Chiellini",
            playerFirstName: "Chiellini",
            playerDate: "April 2, 1990",
            palayerAge: "(age 34)",
            playerHeight: "1.8 m",
            playerPosition: "Defender",
            playerNumber: "5",
            playerJoined: "2005",
            playerGoals: "18",
            playerImage:
              "img/players-position-1/defenders/Chiellini_501x752.png",
            playerId: "#chiellini",
            isChecked: false,
            playerIdNo: 12,
            playerKeywords: ["giorgio", "chiellini", "giorgio chiellini"],
          },
          {
            playerName: "Leonardo Bonucci",
            playerFirstName: "Bonucci",
            playerDate: "May 1, 1987",
            palayerAge: "(age 31)",
            playerHeight: "1.9 m",
            playerPosition: "Defender",
            playerNumber: "19",
            playerJoined: "2010. 2018",
            playerGoals: "15",
            playerImage: "img/players-position-1/defenders/Bonucci_501x752.png",
            playerId: "#bonucci",
            isChecked: false,
            playerIdNo: 13,
            playerKeywords: ["leonardo", "bonucci", "leonardo bonucci"],
          },
          {
            playerName: "Andrea Barzagli",
            playerFirstName: "Barzagli",
            playerDate: "May 8, 1981",
            palayerAge: "(age 37)",
            playerHeight: "1.87 m",
            playerPosition: "Defender",
            playerNumber: "15",
            playerJoined: "2011",
            playerGoals: "2",
            playerImage:
              "img/players-position-1/defenders/Barzagli_501x752.png",
            playerId: "#barzagli",
            isChecked: false,
            playerIdNo: 14,
            playerKeywords: ["andrea", "barzagli", "andrea barzagli"],
          },
          {
            playerName: "Martín Cáceres",
            playerFirstName: "Cáceres",
            playerDate: "May 8, 1981",
            palayerAge: "(age 31)",
            playerHeight: "1.78 m",
            playerPosition: "Defender",
            playerNumber: "4",
            playerJoined: "2009. 2012. 2019",
            playerGoals: "3",
            playerImage: "img/players-position-1/defenders/Caceres_501x752.png",
            playerId: "#caceres",
            isChecked: false,
            playerIdNo: 15,
            playerKeywords: ["martin", "caceres", "martin caceres"],
          },
          {
            playerName: "Alex Sandro",
            playerFirstName: "Alex Sandro",
            playerDate: "January 26, 1991",
            palayerAge: "(age 28)",
            playerHeight: "1.8 m",
            playerPosition: "Defender",
            playerNumber: "12",
            playerJoined: "2015",
            playerGoals: "9",
            playerImage: "img/players-position-1/defenders/SANDRO_501x752.png",
            playerId: "#sandro",
            isChecked: false,
            playerIdNo: 16,
            playerKeywords: ["alex", "sandro", "alex sandro"],
          },
          {
            playerName: "Mattia De Sciglio",
            playerFirstName: "De Sciglio",
            playerDate: "October 20, 1992",
            palayerAge: "(age 26)",
            playerHeight: "1.82 m",
            playerPosition: "Defender",
            playerNumber: "2",
            playerJoined: "2017",
            playerGoals: "Zero",
            playerImage:
              "img/players-position-1/defenders/DeSciglio_501x752.png",
            playerId: "#desciglio",
            isChecked: false,
            playerIdNo: 17,
            playerKeywords: ["joao", "desciglio", "joao desciglio"],
          },
          {
            playerName: "Leonardo Spinazzola",
            playerFirstName: "Spinazzola",
            playerDate: "March 25, 1993",
            palayerAge: "(age 25)",
            playerHeight: "1.86 m",
            playerPosition: "Defender",
            playerNumber: "37",
            playerJoined: "2012",
            playerGoals: "Zero",
            playerImage:
              "img/players-position-1/defenders/Spinazzola_501x752.png",
            playerId: "#spinazzola",
            isChecked: false,
            playerIdNo: 18,
            playerKeywords: ["leonardo", "spinazzola", "leonardo spinazzola"],
          },
          {
            playerName: "Daniele Rugani",
            playerFirstName: "Rugani",
            playerDate: "July 29, 1994",
            palayerAge: "(age 24)",
            playerHeight: "1.86 m",
            playerPosition: "Defender",
            playerNumber: "24",
            playerJoined: "2013",
            playerGoals: "6",
            playerImage: "img/players-position-1/defenders/RUGANI_501x752.png",
            playerId: "#rugani",
            isChecked: false,
            playerIdNo: 19,
            playerKeywords: ["leonardo", "rugani", "leonardo rugani"],
          },
          {
            playerName: "Wojciech Szczęsny",
            playerFirstName: "Szczęsny",
            playerDate: "April 18, 1990",
            palayerAge: "(age 28)",
            playerHeight: "1.95 m",
            playerPosition: "Goalkeeper",
            playerNumber: "1",
            playerJoined: "2017",
            playerGoals: "Zero",
            playerImage:
              "img/players-position-1/goalkeepers/SZCZESNY_501x752.png",
            playerId: "#szczesny",
            isChecked: false,
            playerIdNo: 20,
            playerKeywords: ["leonardo", "szczesny", "leonardo szczesny"],
          },
          {
            playerName: "Mattia Perin",
            playerFirstName: "Perin",
            playerDate: "November 10, 1992",
            palayerAge: "(age 26)",
            playerHeight: "1.88 m",
            playerPosition: "Goalkeeper",
            playerNumber: "22",
            playerJoined: "2018",
            playerGoals: "Zero",
            playerImage: "img/players-position-1/goalkeepers/Perin_501x752.png",
            playerId: "#perin",
            isChecked: false,
            playerIdNo: 21,
            playerKeywords: ["mattia", "perin", "mattia perin"],
          },
          {
            playerName: "Carlo Pinsoglio",
            playerFirstName: "Pinsoglio",
            playerDate: "March 16, 1990",
            palayerAge: "(age 28)",
            playerHeight: "1.94 m",
            playerPosition: "Goalkeeper",
            playerNumber: "31",
            playerJoined: "2014",
            playerGoals: "Zero",
            playerImage:
              "img/players-position-1/goalkeepers/PINSOGLIO_501x752.png",
            playerId: "#pinsoglio",
            isChecked: false,
            playerIdNo: 22,
            playerKeywords: ["carlo", "pinsoglio", "carlo pinsoglio"],
          },
        ],
      };
    });
  },
});
